/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionresidence;

//import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author charlyrenard
 */
public class Signup extends javax.swing.JFrame {

    /**
     *
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        JpnSignUp = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnSignup = new necesario.RSMaterialButtonCircle();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtPrenom = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        LblSignUp = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtMail = new app.bolivia.swing.JCTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtFonction = new app.bolivia.swing.JCTextField();
        txtNom = new app.bolivia.swing.JCTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtDate = new rojeru_san.componentes.RSDateChooser();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtNationalite = new app.bolivia.swing.JCTextField();
        jLabel31 = new javax.swing.JLabel();
        cboSexe = new javax.swing.JComboBox<>();
        txtMatricule = new app.bolivia.swing.JCTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/undraw_building_websites_i78t.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 920, 690));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("STUDENT RESIDENCE MANAGEMENT");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 460, 30));

        jLabel13.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 30, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 970, 800));

        JpnSignUp.setBackground(new java.awt.Color(102, 102, 255));
        JpnSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Sexe :");
        JpnSignUp.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 110, -1));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        JpnSignUp.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 50, 50));

        txtPassword.setBackground(new java.awt.Color(102, 102, 255));
        txtPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        JpnSignUp.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 140, 30));

        btnSignup.setBackground(new java.awt.Color(255, 51, 51));
        btnSignup.setText("SAVE");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        JpnSignUp.add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 700, 260, 50));

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Already have an account ?");
        JpnSignUp.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 760, -1, 30));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        JpnSignUp.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 50));

        txtPrenom.setBackground(new java.awt.Color(102, 102, 255));
        txtPrenom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtPrenom.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtPrenom.setPlaceholder("Entrer prenom...");
        JpnSignUp.add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 270, 40));

        jLabel14.setFont(new java.awt.Font("STHeiti", 0, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Register user");
        JpnSignUp.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        LblSignUp.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        LblSignUp.setForeground(new java.awt.Color(255, 255, 255));
        LblSignUp.setText("Log in");
        LblSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LblSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblSignUpMouseClicked(evt);
            }
        });
        JpnSignUp.add(LblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 760, -1, 30));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Prenom :");
        JpnSignUp.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, -1));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Email :");
        JpnSignUp.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 110, -1));

        txtMail.setBackground(new java.awt.Color(102, 102, 255));
        txtMail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtMail.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtMail.setPlaceholder("Enter Email...");
        JpnSignUp.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 270, 40));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Email(2).png"))); // NOI18N
        JpnSignUp.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 50, 50));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Role.png"))); // NOI18N
        JpnSignUp.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 50, 50));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Fonction :");
        JpnSignUp.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 110, -1));

        txtFonction.setBackground(new java.awt.Color(102, 102, 255));
        txtFonction.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtFonction.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtFonction.setPlaceholder("Enter contact number...");
        JpnSignUp.add(txtFonction, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 270, 40));

        txtNom.setBackground(new java.awt.Color(102, 102, 255));
        txtNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNom.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtNom.setPlaceholder("Entrer nom...");
        txtNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomFocusLost(evt);
            }
        });
        JpnSignUp.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 270, 40));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        JpnSignUp.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, 50));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Nom :");
        JpnSignUp.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, -1));

        jLabel27.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Date de naissance :");
        JpnSignUp.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 200, -1));

        jLabel28.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Birth Date.png"))); // NOI18N
        JpnSignUp.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 50, 50));

        txtDate.setBackground(new java.awt.Color(102, 102, 255));
        txtDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(102, 102, 255)));
        txtDate.setColorBackground(new java.awt.Color(102, 102, 255));
        txtDate.setColorButtonHover(new java.awt.Color(0, 0, 0));
        txtDate.setFormatoFecha("dd/MM/yyyy");
        txtDate.setFuente(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDate.setPlaceholder("Select birthday date");
        JpnSignUp.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 270, -1));

        jLabel29.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Globe.png"))); // NOI18N
        JpnSignUp.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 50, 50));

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Nationalité :");
        JpnSignUp.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, -1));

        txtNationalite.setBackground(new java.awt.Color(102, 102, 255));
        txtNationalite.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNationalite.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtNationalite.setPlaceholder("Entrer nationalité...");
        JpnSignUp.add(txtNationalite, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 270, 40));

        jLabel31.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Password :");
        JpnSignUp.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 110, -1));

        cboSexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "FEMININ", "MASCULIN" }));
        JpnSignUp.add(cboSexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 110, 30));

        txtMatricule.setBackground(new java.awt.Color(102, 102, 255));
        txtMatricule.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtMatricule.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        txtMatricule.setPlaceholder("Entrer matricule...");
        txtMatricule.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatriculeFocusLost(evt);
            }
        });
        JpnSignUp.add(txtMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 270, 40));

        jLabel32.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Matricule.png"))); // NOI18N
        JpnSignUp.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 40, 50));

        jLabel33.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Matricule :");
        JpnSignUp.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, -1));

        getContentPane().add(JpnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 800));

        setSize(new java.awt.Dimension(1350, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);

            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void LblSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblSignUpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LblSignUpMouseClicked

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        String nom = txtNom.getText().toUpperCase();
        String matricule = txtMatricule.getText().toUpperCase();
        String prenom = txtPrenom.getText().toUpperCase();
        String sexe = cboSexe.getSelectedItem().toString().toUpperCase();
        String nationalite = txtNationalite.getText().toUpperCase();
        String mail = txtMail.getText();
        String fonction = txtFonction.getText().toUpperCase();
        String password = txtPassword.getText();
        java.util.Date date = txtDate.getDatoFecha();
        
        Long l1 = date.getTime();
        java.sql.Date fDate = new java.sql.Date(l1);

        //SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YYYY");
        //String date = sdf.format(txtDate.getDatoFecha());
        if (txtNom.getText().isEmpty() || txtPrenom.getText().isEmpty() || txtNationalite.getText().isEmpty() || txtMail.getText().isEmpty()
                || txtFonction.getText().isEmpty() || txtPassword.getText().isEmpty() || txtDate.getDatoFecha() == null || cboSexe.getSelectedIndex() == 0 || txtMatricule.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All data is required", "Avertissement", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                Connection conn = DBConnection.getConnection();
                String query = "INSERT INTO public.utilisateurs(nom, prenom, email, mot_de_passe, fonction, nationalite, date_naissance, sexe, matricule) VALUES (?,?,?,?,?,?,?,?,?)";
                PreparedStatement pst = conn.prepareStatement(query);

                pst.setString(1, nom);
                pst.setString(2, prenom);
                pst.setString(3, mail);
                pst.setString(4, password);
                pst.setString(5, fonction);
                pst.setString(6, nationalite);
                pst.setDate(7, fDate);
                pst.setString(8, sexe);
                pst.setString(9, matricule);

                int updatedRowCount = pst.executeUpdate();

                if (updatedRowCount > 0 ) {
                    JOptionPane.showMessageDialog(null, "Recorded Inserted Successfully !", "Succes", JOptionPane.INFORMATION_MESSAGE);
                    txtNom.setText("");
                    txtPrenom.setText("");
                    txtNationalite.setText("");
                    txtMail.setText("");
                    txtFonction.setText("");
                    txtPassword.setText("");
                    txtDate.setDatoFecha(null);
                    cboSexe.setSelectedIndex(0);
                    txtMatricule.setText("");
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Recorded Insertion Failure !", "Succes", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnSignupActionPerformed

    private void txtNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomFocusLost
        String nom = txtNom.getText();
        if (!txtNom.getText().isEmpty()) {
            try {
                Class.forName("org.postgresql.Driver");
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/gestion_residence", "postgres", "Reinge");
                String query = "SELECT * FROM public.utilisateurs WHERE nom = '" + nom + "'";
                PreparedStatement pst = conn.prepareStatement(query);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "username already exist !", "Message", JOptionPane.INFORMATION_MESSAGE);
                    txtNom.setForeground(Color.red);
                } else {
                    txtNom.setForeground(Color.black);
                }

            } catch (Exception e) {

            }
        } else {
            txtNom.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNomFocusLost

    private void txtMatriculeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnSignUp;
    private javax.swing.JLabel LblSignUp;
    private necesario.RSMaterialButtonCircle btnSignup;
    private javax.swing.JComboBox<String> cboSexe;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.componentes.RSDateChooser txtDate;
    private app.bolivia.swing.JCTextField txtFonction;
    private app.bolivia.swing.JCTextField txtMail;
    private app.bolivia.swing.JCTextField txtMatricule;
    private app.bolivia.swing.JCTextField txtNationalite;
    private app.bolivia.swing.JCTextField txtNom;
    private javax.swing.JPasswordField txtPassword;
    private app.bolivia.swing.JCTextField txtPrenom;
    // End of variables declaration//GEN-END:variables

}
